# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1fab224b1d3f0eac433323fab466d484c539c6b148bae1e8e2217c3e08f23dbd54352e52a5102fda78fbfb6b4f5d61650025a1419abc45664ac045c93859686

test:
  secret_key_base: 92d8d16863b98e3d6548a995df4efce5b147d8aec96635eb00f406f79368dc0f0199b177af0b3b3bde0afe91aa01346347e02fadd7bb597032727ca3aa3a4e44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
